
title: Quest Manager
description: This is a research Project on Quest Managers for games and an explanation on how to implement one on c++ with xml and sdl libraries.
remote_theme: pages-themes/hacker@v0.2.0
